server:
  port: 8099
  servlet-path: /base-login

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/better