server:
  port: 8099
  session:
    timeout: 60

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/better
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: localhost
  session:
    store-type: redis

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: better
      client-secret: better-secret

better:
  security:
    validate:
      img:
        length: 4
#      login-page: /login.html

