server:
  port: 8099
  servlet-path: /

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/better

security:
  basic:
    enabled: false

base-login-security:
  image-prop:
    length: 6
    width: 100
    height: 100
    expire-time: 60
  sms-prop:
    length: 6
    expire-time: 60

